import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from './common/footer';
import styles from '../styles/Xido.module.scss'

import { initializeApp } from "firebase/app";
import { getFirestore, collection, getDocs } from 'firebase/firestore/lite';
import Navigation from './common/navigation';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.left}>
            <Navigation />
            <div className={styles.content}>
              <h1 className={styles.title}>
                <span>로그인</span>
              </h1>
              <p className={styles.description}>
                김민기 대표의 남다른 패션 센스로
                <br/>
                완성된 브랜드 XIDO
                <br/>
                <br/>
                지금 바로 그의 감각을 맛보세요.
              </p>
            </div>
            <Footer />
          </div>
          <div className={styles.right}>
            Right
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
