import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from './common/footer';
import styles from '../styles/Xido.module.scss'

import { initializeApp } from "firebase/app";
import { getFirestore, collection, getDocs } from 'firebase/firestore/lite';
import Navigation from './common/navigation';

const handleSubmit = () => {
  alert("!!");
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.left}>
            <Navigation />
            <div className={styles.content}>
              <h1 className={styles.title}>
                <span>로그인</span>
              </h1>
              <p className={styles.description}>
                김민기 대표의 남다른 패션 센스로
                <br/>
                완성된 브랜드 XIDO
                <br/>
                <br/>
                지금 바로 그의 감각을 맛보세요.
              </p>
            </div>
            <Footer />
          </div>
          <div className={styles.right}>
            <div className={styles.login}>
              <form onSubmit={handleSubmit}>
                <div className={styles.formField}>
                  <div className={styles.inputWrap}>
                    <input type="text" name="userName" autoComplete='userName' placeholder='이메일 또는 확인된 휴대전화 번호'></input>
                    {/* 
                      <label>이메일 또는 확인된 휴대전화 번호</label>
                    */}
                  </div>
                </div>
                <div className={styles.formField}>
                  <div className={styles.inputWrap}>
                    <input type="text" name="password" autoComplete='password' placeholder='비밀번호'></input>
                    {/* 
                      <label>비밀번호</label>
                    */}
                  </div>
                </div>
                <div className={styles.space}></div>
                <button type="submit" className={`${styles.btn} ${styles.btnTransactional} ${styles.loginBtn}`}>
                  <span className={styles.btnCopy}>
                    <span className={styles.btnLabel}>로그인</span>
                  </span>
                </button>
              </form>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
